spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.107/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.107
    port: 6379
server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell/sell.log
#  level:
#    com.imooc.LoggerTest: debug
wechat:
  mpAppId: wx05b60fa24f6e67c9
  mpAppSecret: 545a3641a7617a6d93b5a63638bee6ad
  openAppId: wx6ad144e54af67d87
  openAppSecret: 78778
  mchId: 1483469312
  mchKey: 06C56A89949D617XXXXXXXXX
  keyPath: /var/weixin_cert/h5.p12
  motifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Hhkjhkahfdlafhalfjfda

projectUrl:
  wechatMpAuthorize: http://sell.natapp4.cc
  wechatOpenAuthorize: http://sell.natapp4.cc
  sell: http://sell.natapp4.cc

